index.html.md.erb
We need users to run the Notifications-UI errand on the ERT tile as well as the Notifications errand for emails to send and display correctly.
=> Update to include errand dependency

index.html.md.erb
Signed-off-by: Kira Combs <kcombs@pivotal.io>
=> Updated 1.1 docs [#122226109]

index.html.md.erb
Bumped to 1.0.11; updating 1.0 specific reference docs
=> Added bump release to 1.0 specific docs

index.html.md.erb, sizing.html.md.erb
Signed-off-by: Tom Chen <tochen@pivotal.io>
=> Updated scaling document to reflect considerations for 1.2 [#128539813]

installing.html.md.erb
Signed-off-by: Joseph Rodriguez <jrodriguez@pivotal.io>
=> Add details for alerts section

installing.html.md.erb
=> [#132756559] update docs to require redis version 1.6+

installing.html.md.erb, sizing.html.md.erb
Also updated some small details on scaling.
Signed-off-by: Tom Chen <tochen@pivotal.io>
=> Updated install doc with notes on disabling errands [#130482317]

installing.html.md.erb, troubleshooting.html.md.erb
Signed-off-by: Tom Chen tochen@pivotal.io
=> Add troublshooting for missing logs after update

rn-ki.html.md.erb
Signed-off-by: Tom Chen <tochen@pivotal.io>
=> Updated release notes for metrics 1.2.3

installing.html.md.erb, rn-ki.html.md.erb
Signed-off-by: Johanna Smith <josmith@pivotal.io>
=> Add docs for configuring metrics with GCP

index.html.md.erb, resource-requirements.html.md.erb
Add resource config for 1.2 tile
=> Document the default compute, memory, disk configurations for PCF Metrics

index.html.md.erb, using-custom-metrics.html.md.erb
Signed-off-by: Joseph Rodriguez <jrodriguez@pivotal.io>
=> custom metrics binding #139334849

installing.html.md.erb
https://www.pivotaltracker.com/story/show/140859201
=> Update docs to note correct defaults for errands #140859201

installing.html.md.erb
Change resource config for 1.3
=> Documentation fixes for 1.3

docs-content/installing.html.md.erb, docs-content/rn-ki.html.md.erb
Change 1.4 documentation to reflect the version correctly.
=> Documentation fixed for 1.4

docs-content/using-custom-metrics.html.md.erb
add warning style for service bindings in 1.4
=> Add warning style for service bindings 1.4

installing.html.md.erb, sizing.html.md.erb
Add a table for different sizes when configuring mysql
Signed-off-by: Lisa Cho <lcho@pivotal.io>
=> Update sizing of mysql to include 3 different examples

sizing.html.md.erb
Signed-off-by: Peter Chen <pchen@pivotal.io>
=> update es scaling warning

docs-content/installing.html.md.erb
Signed-off-by: Peter Chen <pchen@pivotal.io>
=> add port information for data services

docs-content/troubleshooting.html.md.erb
Signed-off-by: Peter Chen <pchen@pivotal.io>
=> update 1.4 trouble shooting doc [finishes #148605271]

docs-content/architecture.html.md.erb
Signed-off-by: Todd Persen <tpersen@pivotal.io>
=> update architecture docs for 1.4

index.html.md.erb, monitoringpcfmetrics.html.md.erb
Hi,
The PCF Metrics team was asked to create some documentation about how to monitor our product for health. This is our first-pass attempt at that documentation. The top part is a little wonky, and we weren't sure how to add the title to the subnav. We'd welcome any other feedback you might have.
Thanks!
Elana & Peter
=> Add first pass at docs for monitoring PCF 1.4

rn-ki.html.md.erb
Added 1.4.5 section + release notes
=> Release Notes for PCF Metrics 1.4.5

index.html.md.erb
Updating latest version to 1.4.5, release date, and version compatibility based on supported versions of PAS.
=> Update latest version

rn-ki.html.md.erb
Adding details around the Node.js issue included in 1.4.4.
=> Known issue for 1.4.4

rn-ki.html.md.erb
Added known issue for 'push-app' errand allocation issue.
=> 'push-app' known issue and workaround

rn-ki.html.md.erb
Updated push-apps errand metrics-ui failure to include verbose workaround.
=> push-apps issue + workaround

index.html.md.erb
Updating latest version and release date for 1.4.6.
=> Latest Version Update

rn-ki.html.md.erb
Updating release notes and known issues for the PCF Metrics 1.4.6 maintenance release.
=> Metrics 1.4.6 Maintenance

installing.html.md.erb
Adding data retention configuration bullets to "Configure Metrics Components."
=> Retention Bullets

index.html.md.erb
...yet again. We finally have our OSL, but the team will be out for Thanksgiving and I don't want to release with everyone out. Can we coordinate this push for Monday the 26th?
=> Updating 1.5.1 Release Date

installing.html.md.erb
Correcting some terms in the retention docs, including "buffer" day.
=> Updating Retention Docs

using.html.md.erb
Adding documentation for direct logs and metrics data access.
=> Direct Data Access

using.html.md.erb
=> [#170410055] docs - curl indicators windows

installing.html.md.erb
[#171190871] not sure if i'm including too much information about the environment variables, that's a question for @jbooherl or @ernst-riemer
=> add SOCKS proxy config documentation

sizing.html.md.erb
[#170857670] link out to metric-store and log-store sizing recommendations, and list how to configure sizing for our own resources
recommendations still to come
=> start sizing info

troubleshooting.html.md.erb
[#170857766] describe `/integration-status` and refer to dependencies' docs for troubleshooting
=> troubleshooting dependencies

monitoring-pcf-metrics.html.md.erb
[#170857714]  monitoring -- still use healthwatch, list a couple of basic KPIs
=> monitoring app metrics first pass

using.html.md.erb
[#171547974] add a Note describing behavior of HTTP metrics for non-network apps
=> HTTP metrics for non-Network apps

index.html.md.erb
see [Tracker Story: Fix TBDs on main page](https://www.pivotaltracker.com/story/show/171966300)
=> resolve TBDs in index

index.html.md.erb, using.html.md.erb
see [Tracker Story: Log Store and Metric Store API usage](https://www.pivotaltracker.com/story/show/171987856)
=> Log Store and Metric Store API usage

using.html.md.erb
Needs monitoring schema definined
=> Add monitoring section

using.html.md.erb
Signed off by: Glenn Oppegard <goppegard@vmware.com>
=> Update curl request to log-store with proper get flag

rn-ki.html.md.erb
Signed-off-by: Jeremy Alvis <jalvis@pivotal.io>
=> Add release notes for 2.0.5 [#175208553]

installing.html.md.erb
Add configuration documentation for http proxy support
=> Update installation to include http proxy

using.html.md.erb
Updated information of message component in a query parameter for Querying via HTTP Endpoints.
=> Updated information of message component in a query parameter.

index.html.md.erb, rn-ki.html.md.erb
Reverts pivotal-cf/docs-metrics#168
=> Revert "Release Notes for the App-Metrics 2.1.4"

index.html.md.erb, rn-ki.html.md.erb
Adding release notes for v2.2.2 
Mostly security updates
=> Release notes for 2.2.2

configure-otel-collector.html.md.erb
Expanded out configuration information for the TAS tile to support syslog and otel
=> otel and syslog configuration
